name: Branch Protection

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch protection rules
      run: |
        echo "Branch protection rules are enforced via GitHub's branch protection settings."
        echo "Please ensure the following settings are configured in your repository settings:"
        echo "1. Go to Settings > Branches"
        echo "2. Under 'Branch protection rules', add rule for 'main' and 'master'"
        echo "3. Enable the following options:"
        echo "   - Require a pull request before merging"
        echo "   - Require approvals (recommended: 1 or more)"
        echo "   - Dismiss stale pull request approvals when new commits are pushed"
        echo "   - Require status checks to pass before merging"
        echo "   - Require branches to be up to date before merging"
        echo "   - Require status checks to pass before merging"
        echo "     - build"
        echo "     - test"
        echo "     - lint"
        echo "   - Do not allow bypassing the above settings"

  # This job verifies that required status checks are present
  check-required-checks:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Verify required checks
      run: |
        echo "The following status checks must be required in branch protection rules:"
        echo "- build"
        echo "- test"
        echo "- lint"
        echo "\nMake sure these checks are selected in your branch protection settings."
